language: java
jdk:
- oraclejdk8
dist: trusty
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - $SERVER_IP
cache:
  directories:
  - $HOME/.m2
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
- docker
script:
- docker login -u "$USERNAME" -p "$PASSWD" registry.cn-shenzhen.aliyuncs.com
before_install:
- openssl aes-256-cbc -K $encrypted_801bedcd45e0_key -iv $encrypted_801bedcd45e0_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host "$SERVER_IP"\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- mvn clean package -DskipTests=true
- docker build -t registry.cn-shenzhen.aliyuncs.com/chenjunxinprojects/excelhandle:latest
  .
- docker push registry.cn-shenzhen.aliyuncs.com/chenjunxinprojects/excelhandle:latest
- ssh "$SSHUSERNAME"@"$SERVER_IP" -p "$SERVER_PORT" -o StrictHostKeyChecking=no '.
  /home/chenjunxin/deploy/deployexcelhandle.sh'
