#上传文件存放的盘符路径与下载文件的盘符路径
exceldatahandle:
  uploadFile:
    url: F:\\upload\\
  downloadFile:
    url: F:\\upload\\

#当前Root日志级别变量
logging:
  springframework:
    level: INFO
  mybatis:
    level: INFO
  root:
    level: DEBUG