# \u6A21\u677F\u914D\u7F6E
spring:
  thymeleaf:
        # \u8FD9\u4E2A\u5F00\u53D1\u914D\u7F6E\u4E3Afalse\uFF0C\u907F\u514D\u6539\u4E86\u6A21\u677F\u8FD8\u8981\u91CD\u542F\u670D\u52A1\u5668
        cache: false
       # \u8FD9\u4E2A\u662F\u914D\u7F6E\u6A21\u677F\u8DEF\u5F84\u7684\uFF0C\u9ED8\u8BA4\u5C31\u662Ftemplates\uFF0C\u53EF\u4E0D\u7528\u914D\u7F6E
        prefix: classpath:/templates/
       # \u8FD9\u4E2A\u53EF\u4EE5\u4E0D\u914D\u7F6E\uFF0C\u68C0\u67E5\u6A21\u677F\u4F4D\u7F6E
        check-template-location: true
        # \u4E0B\u97623\u4E2A\u4E0D\u505A\u89E3\u91CA\u4E86\uFF0C\u53EF\u4EE5\u4E0D\u914D\u7F6E
        suffix: .html
        encoding: UTF-8
        # \u6A21\u677F\u7684\u6A21\u5F0F
        mode: HTML5
  profiles:
            active: ${active.file}
server:
  port: 8989
  servlet:
    context-path: /excelhandle

