#上传文件存放的盘符路径与下载文件的盘符路径
exceldatahandle:
  uploadFile:
    url: /home/johnnychan/media/uploadfile/
  downloadFile:
    url: /home/johnnychan/media/uploadfile/

#当前Root日志级别变量
logging:
  config:
    filepath: classpath:log4j2-spring-dev.xml
  springframework:
    level: INFO
  mybatis:
    level: INFO
  root:
    level: DEBUG


