# \u6A21\u677F\u914D\u7F6E
spring:
  thymeleaf:
        # \u8FD9\u4E2A\u5F00\u53D1\u914D\u7F6E\u4E3Afalse\uFF0C\u907F\u514D\u6539\u4E86\u6A21\u677F\u8FD8\u8981\u91CD\u542F\u670D\u52A1\u5668
        cache: false
       # \u8FD9\u4E2A\u662F\u914D\u7F6E\u6A21\u677F\u8DEF\u5F84\u7684\uFF0C\u9ED8\u8BA4\u5C31\u662Ftemplates\uFF0C\u53EF\u4E0D\u7528\u914D\u7F6E
        prefix: classpath:/templates/
       # \u8FD9\u4E2A\u53EF\u4EE5\u4E0D\u914D\u7F6E\uFF0C\u68C0\u67E5\u6A21\u677F\u4F4D\u7F6E
        check-template-location: true
        # \u4E0B\u97623\u4E2A\u4E0D\u505A\u89E3\u91CA\u4E86\uFF0C\u53EF\u4EE5\u4E0D\u914D\u7F6E
        suffix: .html
        encoding: UTF-8
        # \u6A21\u677F\u7684\u6A21\u5F0F
        mode: HTML
  profiles:
#    -Dspring.profiles.active=prod or -Dactive.file=dev-linux
            active: ${active.file}

#  Spring Boot修改最大上传文件限制: 文档说明表示，每个文件的配置最大为1Mb，单次请求的文件的总数不能大于10Mb。
#  要更改这个默认值需要在配置文件（如application.properties）中加入两个配置
  servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB

# 指定 Log4j2 配置文件
logging:
  config: ${logging.config.filepath}
  level:
    org:
      springframework: ${logging.springframework.level}
      mybatis: ${logging.mybatis.level}
    root: ${logging.root.level}

#  level:
#    com.chenjunxin: warn

# Spring Boot Actuator组件配置 Actuator 几乎监控了应用涉及的方方面面
#在 Spring Boot 2.x 中为了安全期间，Actuator 只开放了两个端点 /actuator/health 和 /actuator/info。可以在配置文件中设置打开。
#可以打开所有的监控点 management.endpoints.web.exposure.include=*
#也可以选择打开部分  management.endpoints.web.exposure.exclude=beans,trace
#Actuator 默认所有的监控点路径都在/actuator/*，当然如果有需要这个路径也支持定制。management.endpoints.web.base-path=/manage
#设置完重启后，再次访问地址就会变成/manage/*
management:
  endpoints:
    web:
      exposure:
        include: loggers

server:
  port: 8989
  servlet:
    context-path: /excelhandle